services:
  - type: web
    name: my-travel-journal
    env: docker
    plan: free
    branch: main
    dockerfilePath: ./Dockerfile
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: sql7.freesqldatabase.com
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: sql7783472
      - key: DB_USERNAME
        value: sql7783472
      - key: DB_PASSWORD
        value: 1wrXf1lKfs
